package gui;

import classes.OrdemServico;
import excecoes.os.OSNaoAbertaException;
import excecoes.os.OSNaoEncontradaException;
import oficina.Oficina;

/**
 *
 * @author joovitor
 */
public class JanelaGerenciarOS extends javax.swing.JFrame {

    private OrdemServico ordemServico;
    private JanelaOS jos;
    
    public JanelaGerenciarOS(OrdemServico ordemServico, JanelaOS jos) {
        initComponents();
        this.jos = jos;
        this.ordemServico = ordemServico;
        tNum.setText(this.ordemServico.getNumeroOS()+"");
        tData.setText(this.ordemServico.getDataOS().toString());
        tDataPrev.setText(this.ordemServico.getDataPrevTermino().toString());
        if(this.ordemServico.getDataTermino() == null)
        {
            tDataTerm.setText("null");
        }else{
            tDataTerm.setText(this.ordemServico.getDataTermino().toString());
        }
        tPlaca.setText(this.ordemServico.getPlacaCarro());
        if(this.ordemServico.getSituação()=='A')
        {
            tSituacao.setText("Aberta");
        }else if(this.ordemServico.getSituação()=='C'){
            tSituacao.setText("Cancelada");
        }else if(this.ordemServico.getSituação()=='F'){
            tSituacao.setText("Finalizada");
        }
        tProprietario.setText(this.ordemServico.getCliente().getNome());
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tValor = new javax.swing.JTextField();
        tNum = new javax.swing.JTextField();
        tData = new javax.swing.JTextField();
        tDataPrev = new javax.swing.JTextField();
        tDataTerm = new javax.swing.JTextField();
        tPlaca = new javax.swing.JTextField();
        tSituacao = new javax.swing.JTextField();
        bProduto = new javax.swing.JButton();
        bFinalizar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tProprietario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NumeroOS:");

        jLabel2.setText("DataOS:");

        jLabel3.setText("Previsão Termino");

        jLabel4.setText("Data Termino");

        jLabel5.setText("Placa");

        jLabel6.setText("Situação");

        jLabel7.setText("Valor");

        tValor.setEditable(false);

        tNum.setEditable(false);

        tData.setEditable(false);

        tDataPrev.setEditable(false);

        tDataTerm.setEditable(false);

        tPlaca.setEditable(false);

        tSituacao.setEditable(false);

        bProduto.setText("Produtos");
        bProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProdutoActionPerformed(evt);
            }
        });

        bFinalizar.setText("FinalizarOS");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        bCancelar.setText("CancelarOS");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Proprietario:");

        tProprietario.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tDataTerm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(tDataPrev, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tData, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tPlaca))
                                .addContainerGap())
                            .addComponent(tSituacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tProprietario))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(bFinalizar)
                                .addGap(18, 18, 18)
                                .addComponent(bCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(bProduto)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tDataPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDataTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bProduto)
                    .addComponent(bFinalizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        String titulo = "Finalizar OS";
        
        try
        {
            Oficina.finalizarOS(this.ordemServico.getNumeroOS());
            this.jos.atualizarTabela();
        }catch(OSNaoAbertaException | OSNaoEncontradaException ex){
            Mensagem.exibirMensagemErro(titulo, ex.getMessage());
        }
    }//GEN-LAST:event_bFinalizarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        String titulo = "Cancelar OS";
        
        try
        {
            Oficina.cancelarOS(this.ordemServico.getNumeroOS());
            this.jos.atualizarTabela();
        }catch(OSNaoAbertaException | OSNaoEncontradaException ex){
            Mensagem.exibirMensagemErro(titulo, ex.getMessage());
        }
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProdutoActionPerformed
        new JanelaItemOS(ordemServico,this.jos);
        dispose();
    }//GEN-LAST:event_bProdutoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tData;
    private javax.swing.JTextField tDataPrev;
    private javax.swing.JTextField tDataTerm;
    private javax.swing.JTextField tNum;
    private javax.swing.JTextField tPlaca;
    private javax.swing.JTextField tProprietario;
    private javax.swing.JTextField tSituacao;
    private javax.swing.JTextField tValor;
    // End of variables declaration//GEN-END:variables
}
