/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Cliente;
import classes.OrdemServico;
import classes.Peca;
import classes.Servico;
import java.util.ArrayList;
import operacoes.IO;

/**
 *
 * @author joovitor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private ArrayList<Cliente> listaClientes; 
    private ArrayList<OrdemServico> listaOS;
    private ArrayList<Peca> listaPecas; 
    private ArrayList<Servico> listaServicos;
    
    public MenuPrincipal(ArrayList<Cliente> listaClientes, ArrayList<OrdemServico> listaOS,
            ArrayList<Peca> listaPecas, ArrayList<Servico> listaServicos) {
        initComponents();
        this.listaClientes = listaClientes;
        this.listaOS = listaOS;
        this.listaPecas = listaPecas;
        this.listaServicos = listaServicos;
        this.setLocationRelativeTo(null); 
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSair = new javax.swing.JButton();
        bCli = new javax.swing.JButton();
        bProd = new javax.swing.JButton();
        bOS = new javax.swing.JButton();
        bTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bSair.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        bSair.setText("Sair do programa");
        bSair.setActionCommand("Gerênciar Ordens de Serviço");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        bCli.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        bCli.setText("Gerênciar Clientes");
        bCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCliActionPerformed(evt);
            }
        });

        bProd.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        bProd.setText("Gerênciar Produtos");
        bProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProdActionPerformed(evt);
            }
        });

        bOS.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        bOS.setText("Gerênciar Ordens de Serviço");
        bOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOSActionPerformed(evt);
            }
        });

        bTotal.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        bTotal.setText("Consultar total vendido em um periodo");
        bTotal.setActionCommand("Gerênciar Ordens de Serviço");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bOS, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(bTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bProd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCliActionPerformed
        new JanelaCliente(listaClientes);
    }//GEN-LAST:event_bCliActionPerformed

    private void bProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bProdActionPerformed

    private void bOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOSActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTotalActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        IO.gravarClientes(listaClientes);
        IO.gravarOS(listaOS);
        IO.gravarPecas(listaPecas);
        IO.gravarServicos(listaServicos);
        System.exit(0);
    }//GEN-LAST:event_bSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        IO.gravarClientes(listaClientes);
        IO.gravarOS(listaOS);
        IO.gravarPecas(listaPecas);
        IO.gravarServicos(listaServicos);
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCli;
    private javax.swing.JButton bOS;
    private javax.swing.JButton bProd;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bTotal;
    // End of variables declaration//GEN-END:variables
}
