/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Peca;
import classes.Produto;
import classes.Servico;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joovitor
 */
public class ProdutoEncontrado extends javax.swing.JFrame {

    private ArrayList<Produto> produtos;
    
    public ProdutoEncontrado(ArrayList<Produto> produtos) {
        initComponents();
        this.produtos = produtos;
        this.tProcurar.requestFocus();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEncontrados = new javax.swing.JTable();
        tProcurar = new javax.swing.JTextField();
        bProcurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos encontrados:"));

        tabelaEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Código", "Descrição", "Preço", "Estoque", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEncontrados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaEncontrados);

        bProcurar.setText("Procurar");
        bProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(tProcurar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(bProcurar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bProcurar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcurarActionPerformed
        String nome = tProcurar.getText();
        atualizarTabela(nome);
    }//GEN-LAST:event_bProcurarActionPerformed

    public void atualizarTabela(String nome)
    {
        DefaultTableModel tabela = (DefaultTableModel)this.tabelaEncontrados.getModel();
        
        while(tabela.getRowCount() > 0)
        {
            tabela.removeRow(0);
        }
        
        String tipo;
        String codigo;
        String preco;
        String descricao;
        for (Produto produto : produtos) {
            if(produto.getDescricao().toLowerCase().contains(nome.toLowerCase()))
            {
                codigo = String.valueOf(produto.getCodigo());
                preco = String.valueOf(produto.getPreco());
                descricao = produto.getDescricao();
                String qtdEstoque = "";
                String tempoDuracao = "";
                if(produto instanceof Peca)
                {
                    tipo = "Peça";
                    qtdEstoque = String.valueOf(((Peca) produto).getQtdeEstoque());

                    Object [] dado = {tipo,codigo,descricao,preco,qtdEstoque,tempoDuracao};
                    tabela.addRow(dado);
                }
                else if(produto instanceof Servico)
                {
                    tipo = "Serviço";
                    tempoDuracao = ((Servico)produto).getTempoExecucaoString();

                    Object [] dado = {tipo,codigo,descricao,preco,qtdEstoque,tempoDuracao};
                    tabela.addRow(dado);
                }
            }
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bProcurar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tProcurar;
    private javax.swing.JTable tabelaEncontrados;
    // End of variables declaration//GEN-END:variables
}
