package gui.os;

import classes.Cliente;
import classes.OrdemServico;
import excecoes.CampoVazioException;
import excecoes.cliente.ClienteNaoEncontradoException;
import excecoes.DataInvalidaException;
import gui.Mensagem;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import oficina.Oficina;

public class JanelaAbrirOS extends javax.swing.JFrame {

    private ArrayList<OrdemServico> ordensServico;
    private JanelaOS janelaOS;
    
    public JanelaAbrirOS(ArrayList<OrdemServico> ordensServico, JanelaOS janelaOS) {
        initComponents();
        this.ordensServico = ordensServico;
        this.janelaOS = janelaOS;
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDataPrevistaTermino = new javax.swing.JLabel();
        labelPlacaVeiculo = new javax.swing.JLabel();
        labelCpfCliente = new javax.swing.JLabel();
        textDataPrevistaTermino = new javax.swing.JTextField();
        textPlacaVeiculo = new javax.swing.JTextField();
        textCpfCliente = new javax.swing.JTextField();
        botaoAbrirOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abrir OS - Controle de Oficina");
        setResizable(false);

        labelDataPrevistaTermino.setText("Data prevista para término:");

        labelPlacaVeiculo.setText("Placa do veículo:");

        labelCpfCliente.setText("CPF do cliente:");

        botaoAbrirOS.setText("Abrir OS");
        botaoAbrirOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAbrirOS))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCpfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPlacaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDataPrevistaTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCpfCliente)
                            .addComponent(textPlacaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(textDataPrevistaTermino, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataPrevistaTermino)
                    .addComponent(textDataPrevistaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlacaVeiculo)
                    .addComponent(textPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfCliente)
                    .addComponent(textCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAbrirOS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAbrirOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirOSActionPerformed
        String titulo = "Abrir OS";
        
        String dataPrev = textDataPrevistaTermino.getText();
        String placa = textPlacaVeiculo.getText();
        String cpf = textCpfCliente.getText();
        
        try {
            Cliente cliente = Oficina.buscarCliente(cpf);
            ordensServico.add(new OrdemServico(dataPrev, placa, cliente));
            this.janelaOS.atualizarTabela();
            Mensagem.exibirMensagem(titulo, "OS aberta com sucesso!");
            dispose();
        } catch(ClienteNaoEncontradoException | DataInvalidaException | CampoVazioException e){
            Mensagem.exibirMensagemErro(titulo, e.getMessage());
        } catch (DateTimeParseException e) {
            Mensagem.exibirMensagemErro(titulo, "Não foi possível converter o texto em data");
        }
    }//GEN-LAST:event_botaoAbrirOSActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbrirOS;
    private javax.swing.JLabel labelCpfCliente;
    private javax.swing.JLabel labelDataPrevistaTermino;
    private javax.swing.JLabel labelPlacaVeiculo;
    private javax.swing.JTextField textCpfCliente;
    private javax.swing.JTextField textDataPrevistaTermino;
    private javax.swing.JTextField textPlacaVeiculo;
    // End of variables declaration//GEN-END:variables
}
