package gui.os;

import classes.OrdemServico;
import excecoes.os.OSNaoAbertaException;
import excecoes.os.OSNaoEncontradaException;
import gui.Mensagem;
import oficina.Oficina;

public class JanelaGerenciarOS extends javax.swing.JFrame {

    private OrdemServico ordemServico;
    private JanelaOS janelaOS;
    
    public JanelaGerenciarOS(OrdemServico ordemServico, JanelaOS janelaOS) {
        initComponents();
        this.janelaOS = janelaOS;
        this.ordemServico = ordemServico;
        atualizar();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNumero = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelPrevisaoTermino = new javax.swing.JLabel();
        labelDataTermino = new javax.swing.JLabel();
        labelPlacaVeiculo = new javax.swing.JLabel();
        labelSituacao = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        textValor = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        textData = new javax.swing.JTextField();
        textPrevisaoTermino = new javax.swing.JTextField();
        textDataTermino = new javax.swing.JTextField();
        textPlacaVeiculo = new javax.swing.JTextField();
        textSituacao = new javax.swing.JTextField();
        labelProprietario = new javax.swing.JLabel();
        textProprietario = new javax.swing.JTextField();
        panelBotoes = new javax.swing.JPanel();
        botaoFinalizar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoItens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar OS - Controle de Oficina");
        setResizable(false);

        labelNumero.setText("Número:");

        labelData.setText("Data:");

        labelPrevisaoTermino.setText("Previsão de Término:");

        labelDataTermino.setText("Data de Término:");

        labelPlacaVeiculo.setText("Placa do Veículo:");

        labelSituacao.setText("Situação:");

        labelValor.setText("Valor:");

        textValor.setEditable(false);

        textNumero.setEditable(false);

        textData.setEditable(false);

        textPrevisaoTermino.setEditable(false);

        textDataTermino.setEditable(false);

        textPlacaVeiculo.setEditable(false);

        textSituacao.setEditable(false);

        labelProprietario.setText("Proprietario:");

        textProprietario.setEditable(false);

        botaoFinalizar.setText("Finalizar OS");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });
        panelBotoes.add(botaoFinalizar);

        botaoCancelar.setText(" Cancelar OS");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        panelBotoes.add(botaoCancelar);

        botaoItens.setText("Itens");
        botaoItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoItensActionPerformed(evt);
            }
        });
        panelBotoes.add(botaoItens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumero)
                            .addComponent(labelData)
                            .addComponent(labelPrevisaoTermino)
                            .addComponent(labelPlacaVeiculo)
                            .addComponent(labelDataTermino)
                            .addComponent(labelSituacao)
                            .addComponent(labelValor)
                            .addComponent(labelProprietario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(textPrevisaoTermino, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDataTermino, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textPlacaVeiculo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textData)
                            .addComponent(textNumero)
                            .addComponent(textSituacao)
                            .addComponent(textValor))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrevisaoTermino)
                    .addComponent(textPrevisaoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataTermino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlacaVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSituacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProprietario)
                    .addComponent(textProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        String titulo = "Finalizar OS";
        
        try
        {
            Oficina.finalizarOS(this.ordemServico.getNumeroOS());
            this.janelaOS.atualizarTabela();
            atualizar();
        }catch(OSNaoAbertaException | OSNaoEncontradaException ex){
            Mensagem.exibirMensagemErro(titulo, ex.getMessage());
        }
    }//GEN-LAST:event_botaoFinalizarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        String titulo = "Cancelar OS";
        
        try
        {
            Oficina.cancelarOS(this.ordemServico.getNumeroOS());
            this.janelaOS.atualizarTabela();
            atualizar();
        }catch(OSNaoAbertaException | OSNaoEncontradaException ex){
            Mensagem.exibirMensagemErro(titulo, ex.getMessage());
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoItensActionPerformed
        new JanelaItemOS(ordemServico,this.janelaOS);
        dispose();
    }//GEN-LAST:event_botaoItensActionPerformed
    
    private void atualizar() {
        textNumero.setText(this.ordemServico.getNumeroOS()+"");
        textData.setText(this.ordemServico.getDataOS().toString());
        textPrevisaoTermino.setText(this.ordemServico.getDataPrevTermino().toString());
        if(this.ordemServico.getDataTermino() == null)
        {
            textDataTermino.setText("");
        }else{
            textDataTermino.setText(this.ordemServico.getDataTermino().toString());
        }
        textPlacaVeiculo.setText(this.ordemServico.getPlacaCarro());
        
        if(this.ordemServico.getSituacao() != 'A'){
            botaoCancelar.setEnabled(false);
            botaoFinalizar.setEnabled(false);
        }
        
        switch (this.ordemServico.getSituacao()) {
            case 'A' -> textSituacao.setText("Aberta");
            case 'C' -> textSituacao.setText("Cancelada");
            case 'F' -> textSituacao.setText("Finalizada");
            default -> {
            }
        }
        textProprietario.setText(this.ordemServico.getCliente().getNome());
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JButton botaoItens;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDataTermino;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPlacaVeiculo;
    private javax.swing.JLabel labelPrevisaoTermino;
    private javax.swing.JLabel labelProprietario;
    private javax.swing.JLabel labelSituacao;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textDataTermino;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textPlacaVeiculo;
    private javax.swing.JTextField textPrevisaoTermino;
    private javax.swing.JTextField textProprietario;
    private javax.swing.JTextField textSituacao;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
