package gui.produto;

import classes.Servico;
import excecoes.CampoVazioException;
import excecoes.produto.PrecoInvalidoException;
import gui.Mensagem;

public class EdicaoServico extends javax.swing.JFrame {

    private Servico servico;
    private JanelaProdutos janelaProduto;
    
    public EdicaoServico(Servico servico, JanelaProdutos janelaProduto) {
        initComponents();
        this.servico = servico;
        this.janelaProduto = janelaProduto;
        textDescricao.setText(servico.getDescricao());
        textPreco.setText(servico.getPreco()+"");
        String[] partes = servico.getTempoExecucaoString().split(":");
        textDias.setText(partes[0]);
        textHoras.setText(partes[1]);
        textMinutos.setText(partes[2]);
        textSegundos.setText(partes[3]);
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDescricao = new javax.swing.JLabel();
        textDescricao = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        textPreco = new javax.swing.JTextField();
        botaoEditar = new javax.swing.JButton();
        panelDuracao = new javax.swing.JPanel();
        labelDias = new javax.swing.JLabel();
        textDias = new javax.swing.JTextField();
        labelHoras = new javax.swing.JLabel();
        textHoras = new javax.swing.JTextField();
        labelMinutos = new javax.swing.JLabel();
        textMinutos = new javax.swing.JTextField();
        labelSegundos = new javax.swing.JLabel();
        textSegundos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labelDescricao.setText("Descrição:");

        labelPreco.setText("Preço:");

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        panelDuracao.setBorder(javax.swing.BorderFactory.createTitledBorder("Duração"));

        labelDias.setText("Dia(s):");

        labelHoras.setText("Hora(s):");

        labelMinutos.setText("Minuto(s):");

        labelSegundos.setText("Segundo(s):");

        javax.swing.GroupLayout panelDuracaoLayout = new javax.swing.GroupLayout(panelDuracao);
        panelDuracao.setLayout(panelDuracaoLayout);
        panelDuracaoLayout.setHorizontalGroup(
            panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDuracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDuracaoLayout.createSequentialGroup()
                        .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDias)
                            .addComponent(textHoras)))
                    .addGroup(panelDuracaoLayout.createSequentialGroup()
                        .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMinutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMinutos, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(textSegundos))))
                .addContainerGap())
        );
        panelDuracaoLayout.setVerticalGroup(
            panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDuracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDias)
                    .addComponent(textDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoras)
                    .addComponent(textHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinutos)
                    .addComponent(textMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSegundos)
                    .addComponent(textSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(textDescricao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao)
                    .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreco)
                    .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        String titulo = "Edição Peça";
        try {
            servico.setDescricao(textDescricao.getText());
            servico.setPreco(Double.parseDouble(textPreco.getText()));
            int dia,hora,minuto,segundo;
            dia = Integer.parseInt(textDias.getText());
            hora = Integer.parseInt(textHoras.getText());
            minuto = Integer.parseInt(textMinutos.getText());
            segundo = Integer.parseInt(textSegundos.getText());
            servico.setTempoExecucao(dia, hora, minuto, segundo);
            
            janelaProduto.atualizarTabela();
            Mensagem.exibirMensagem(titulo, "Atualização bem sucedida!");
            dispose();
        } catch (PrecoInvalidoException | CampoVazioException e) {
            Mensagem.exibirMensagemErro(titulo, e.getMessage());
        } catch (NumberFormatException e) {
            Mensagem.exibirMensagemErro(titulo, "Algum campo numérico está com um valor inválido ou vazio");
        } 
    }//GEN-LAST:event_botaoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelDias;
    private javax.swing.JLabel labelHoras;
    private javax.swing.JLabel labelMinutos;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelSegundos;
    private javax.swing.JPanel panelDuracao;
    private javax.swing.JTextField textDescricao;
    private javax.swing.JTextField textDias;
    private javax.swing.JTextField textHoras;
    private javax.swing.JTextField textMinutos;
    private javax.swing.JTextField textPreco;
    private javax.swing.JTextField textSegundos;
    // End of variables declaration//GEN-END:variables
}
