package gui.produto;

import classes.Peca;
import excecoes.CampoVazioException;
import excecoes.produto.PrecoInvalidoException;
import excecoes.produto.peca.QuantidadeEstoqueInvalidaException;
import gui.Mensagem;

public class EdicaoPeca extends javax.swing.JFrame {

    private Peca peca;
    private JanelaProdutos janelaProduto;
    
    public EdicaoPeca(Peca peca, JanelaProdutos janelaProduto) {
        initComponents();
        this.peca = peca;
        this.janelaProduto = janelaProduto;
        this.textDescricao.setText(peca.getDescricao()+"");
        this.textPreco.setText(peca.getPreco()+"");
        this.textEstoque.setText(peca.getQtdeEstoque()+"");
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDescricao = new javax.swing.JLabel();
        textDescricao = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        textPreco = new javax.swing.JTextField();
        labelEstoque = new javax.swing.JLabel();
        textEstoque = new javax.swing.JTextField();
        botaoEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Peça - Controle de Oficina");
        setResizable(false);

        labelDescricao.setText("Descrição:");

        labelPreco.setText("Preço:");

        labelEstoque.setText("Estoque: ");

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDescricao)
                    .addComponent(textPreco)
                    .addComponent(textEstoque)
                    .addComponent(botaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao)
                    .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreco)
                    .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstoque)
                    .addComponent(textEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(botaoEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        String titulo = "Editar Peça";
        try {
            peca.setDescricao(textDescricao.getText());
            peca.setPreco(Double.parseDouble(textPreco.getText()));
            peca.setQtdeEstoque(Integer.parseInt(textEstoque.getText()));
            janelaProduto.atualizarTabela();
            Mensagem.exibirMensagem(titulo, "Atualização bem sucedida!");
            dispose();
        } catch (PrecoInvalidoException | QuantidadeEstoqueInvalidaException | CampoVazioException e) {
            Mensagem.exibirMensagemErro(titulo, e.getMessage());
        } catch (NumberFormatException e) {
            Mensagem.exibirMensagemErro(titulo, "Algum campo numérico está com um valor inválido ou vazio");
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelEstoque;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JTextField textDescricao;
    private javax.swing.JTextField textEstoque;
    private javax.swing.JTextField textPreco;
    // End of variables declaration//GEN-END:variables
}
